### ISSUE TITLE
[9/29/23] Updated release of BuildingSync 2.5 Milestone

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#465]
- upload GHG Use Case to website
- add GHG example to schema repo

**Comment by laurenliz22** [comment]
- Make sure we update the schematron during this release

**Comment by JieXiong9119** [comment]
Schema repo

- [ ] Schema xsd
- [ ] Jupyter notebooks and examples
- [ ] Docs
- [ ] CHANGELOG

Use case

- [ ] Schematrons and (source csvs)
- [ ] Examples

bsyncpy

- [ ] Add elements
- [ ] Release package

BuildingSync-gem

- [ ] 

Website

- [ ] Update all versioning fields
- [ ] Link to Schema 2.5
- [ ] Update validator, use cases, examples
